name: Deploy Astro to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2. Setup Node (for runtime)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # 3. Install the PNPM CLI
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      # 4. Install project dependencies
      - name: Install dependencies
        run: pnpm install

      # 5. Build your Astro site
      - name: Build site
        run: pnpm astro build

      # 6. Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
